# Generated by Django 6.0 on 2026-01-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0003_auto_20220904_2045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="file",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="A file to be uploaded and linked to instead of the URL.",
                max_length=500,
                null=True,
                upload_to="uploads/",
            ),
        ),
    ]
