name: Fly Deploy
concurrency: deploy
on:
  workflow_run:
    workflows:
      - CI
    branches:
      - main
    types:
      - completed
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@dfdfedc86b296f5e5384f755a18bf400409a15d0
      - run: flyctl deploy --remote-only
